# Generated by Django 3.1.2 on 2022-01-22 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_auto_20220119_1949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directivos',
            new_name='Directivo',
        ),
        migrations.RenameModel(
            old_name='Docentes',
            new_name='Docente',
        ),
    ]
