# Generated by Django 3.1.2 on 2022-02-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0014_auto_20220213_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='año',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='turno',
            field=models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde')], max_length=6, null=True, verbose_name='turno'),
        ),
    ]
