# Generated by Django 3.1.2 on 2022-02-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0016_directivo_telefono_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='telefono_contacto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='directivo',
            name='telefono_contacto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='telefono_contacto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
