# Generated by Django 3.1.2 on 2022-02-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0017_auto_20220214_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
