# Generated by Django 4.0.1 on 2022-02-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0023_alumno_imagen_directivo_imagen_docente_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='año_nacimiento',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='domicilio_calle',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='domicilio_calleNumero',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='domicilio_cp',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='domicilio_localidad',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='provincia',
        ),
    ]
